title: Luca Franceschini
author: "" # GitHub User
email: lucaf@lucaf.eu
description: "" #> # this means to ignore newlines until "twitter_username:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# social links
github_username:  lucafrance
linkedin_username: lucaf-munich
rss: rss
# twitter_username: ""
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %B %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - blog.html
  - tags.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Custom, not part of default minima _config.yml


exclude:
  - /*.ps1
  - Gemfile
  - Gemfile.lock

# Use the "post" layout for all posts without having to specify it every time
defaults:
  - 
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "post"
